name: Check Go library
on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  check-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: bufbuild/buf-setup-action@v1.27.0
        with:
          version: 1.27.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check generated code is up to date
        run: |
          make buf-generated-srcs
          git diff --exit-code HEAD

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit tests
        run: |
          make unit-tests
